### PR TITLE
Add layout, zoom, and rotate controls to media/show.

### PR DESCRIPTION
**Pull request by kimisgold**

### CODE REVIEW

**Comment by jimsafley** [comment]
Ubuntu 16.04 | Google Chrome 65.0.3325.181

- On every page but "Media review" I'm getting the following JS error:
```
jQuery.Deferred exception: $(...).featherlight is not a function TypeError: $(...).featherlight is not a function
    at HTMLDocument.<anonymous> (http://localhost/omeka-s/modules/Scripto/asset/js/scripto.js?v=0.1.0-alpha:46:27)
    at j (http://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js:2:29999)
    at k (http://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js:2:30313) undefined
Uncaught TypeError: $(...).featherlight is not a function
    at HTMLDocument.<anonymous> (scripto.js?v=0.1.0-alpha:46)
    at j (jquery.min.js:2)
    at k (jquery.min.js:2)
```
- On "Media review" I'm getting the following JS error when attempting to rotate a non-image media (YouTube, HTML, etc.):
```
Uncaught TypeError: Cannot read property 'split' of undefined
    at getRotationDegrees (scripto.js?v=0.1.0-alpha:9)
    at setRotation (scripto.js?v=0.1.0-alpha:19)
    at HTMLButtonElement.<anonymous> (scripto.js?v=0.1.0-alpha:63)
    at HTMLDivElement.dispatch (jquery.min.js:3)
    at HTMLDivElement.q.handle (jquery.min.js:3)
``` 
- On "Media review" the pan-zoom container is pushed to the right when rendering non-image media (HTML shown).
untitled media review scripto whoameka
- Pan, zoom, and rotation should probably only be available for images.
- Also, you'll notice that the "Go full screen" icon is not rendering and that the pagination is taking up vertical space.
- My personal preference is for the "Go full screen," "Horizontal view," and "Vertical view" buttons to be smaller or use their respective icons, if they exist.
- When rotating I see JS debugging output in the console that needs to be removed.
- The zoom controls stop working after switching to full screen (no JS error).
- Switching to full screen should preserve the selected layout, and vise versa.
- Ideally, in full screen, the lightbox should not change shape when switching from horizontal to vertical view:
vert
horiz
- There is no "Approval history" or "Completion history."
- The "Review media" sidebar is hidden under the existing "Media metadata" sidebar. Perhaps we can integrate the review controls at the top of the "Media metadata" sidebar.
- My personal preference is for the review controls to be wide buttons instead of checkboxes for quicker review. The button text could contain something like, "Approved. Click to mark as not approved." and "Not approved. Click to approve."

**Comment by kimisgold** [comment]
@jimsafley I think I've addressed most of your comments, with the exception of the review controls as buttons instead of checkboxes—still chewing on that, as I don't believe that buttons would be faster (since the labels activate the checkboxes as well), but it seems less essential for the moment.

**Comment by jimsafley** [comment]
A few things that still need addressing:

* I'm concerned that we're losing consistency by moving the media metadata from the sidebar to a tab (project and item metadata are in a sidebar). Perhaps we can integrate the review controls at the top of the "Media metadata" sidebar.
* Ideally, in full screen, the lightbox should not change shape when switching from horizontal to vertical view. It's a bit jarring to me, but I suppose it makes sense given how the re-orientation changes the height.
* There is no "Approval history" or "Completion history." You can remove the "View history" links and the "Completion history" sidebar.

**Comment by kimisgold** [comment]
The latest commits should address your most recent points.

**Comment by jimsafley** [comment]
Thanks for the fixes. They look good.

About the media review form: I don't feel that "Approval status" or "Completion status" followed by a checkbox is very clear to the reviewer. Forget my earlier suggestion of a button. Fundamentally I feel that a) the current status should be abundantly clear at a glance, and b) that the toggle between statuses should be equally clear and quickly toggled. I'm going to merge this PR, but let's iterate through some ideas (with @mebrett's and @alyssafahringer's help) about how to best present the review form.

By the way, I'll eventually have more additions to the review form, so there's a need to further streamline and conserve space.

**Pull request merged**
