### PR TITLE
Make media views more useful.

### PR DESCRIPTION
**Pull request by kimisgold**
* Provide edit links on the browse view. (#42)
* Prioritize media's association with a document/item over potential garbled filenames. (#44)
* Hide empty media metadata column. (#45)

### CODE REVIEW

**Comment by mebrett** [comment]
Looks good to me. @jdauteri If you want to see what it looks like, I have that branch checked out for http://dev.omeka.org/omeka-s/scripto/3/item

**Comment by jdauteri** [comment]
This looks good to me, too. However, I can no longer click on the thumbnails to access each media view. Not sure if this was intentional or not, but I thought I'd note it here either way.

**Comment by kimisgold** [comment]
@jdauteri That was an oversight that I've just corrected, thanks! Since everything else checks out, I'll go ahead and merge this then.

**Comment by mebrett** [comment]
I've updated the shared install's Scripto to the latest on Master

**Pull request merged**
